version: "3"

services:
  proxy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./:/app
    command: npx nx serve backend
