version: "3"

services:

  api:
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    networks:
      - proxy
    restart: unless-stopped

  database:
    image: postgres:13.2-alpine
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carbon
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: local@localhost.local
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres-data:

networks:
  proxy:
    external: true
