-- AlterTable
ALTER TABLE "User" ALTER COLUMN "entryDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "experience" DROP NOT NULL,
ALTER COLUMN "experience" SET DEFAULT 0,
ALTER COLUMN "role" SET DEFAULT 'user';
