export const FrameworkValues = {
  VUEJS: "Vue.js",
  DJANGO: "Django",
  RUBYONRAILS: "Ruby on Rails",
  LARAVEL: "Laravel",
  SPRINGBOOT: "Spring Boot",
  EXPRESSJS: "Express.js",
  ASPNET: "ASP.NET",
  FLASK: "Flask",
  EMBERJS: "Ember.js",
  ASPNETCORE: "ASP.NET Core",
  SYMFONY: "Symfony",
  FLUTTER: "Flutter",
  XAMARIN: "Xamarin",
  METEOR: "Meteor",
  CAKEPHP: "CakePHP",
  CODEIGNITER: "CodeIgniter",
  ZENDFRAMEWORK: "Zend Framework",
  RUBYMOTION: "RubyMotion",
  BACKBONEJS: "Backbone.js",
  METEORJS: "Meteor.js",
  AURELIA: "Aurelia",
  KNOCKOUTJS: "Knockout.js",
  NEXTJS: "Next.js",
  ELECTRON: "Electron",
  NESTJS: "NestJS",
  STRUTS: "Struts",
  GRAILS: "Grails",
  MOJOLICIOUS: "Mojolicious",
  FALCON: "Falcon",
  HAPIJS: "Hapi.js",
  KOAJS: "Koa.js",
  PHOENIX: "Phoenix",
  SINATRA: "Sinatra",
  ADONISJS: "AdonisJS",
  GINATRA: "Ginatra",
  REVEL: "Revel",
  BEEGO: "Beego",
  MARTINI: "Martini",
  BUFFALO: "Buffalo",
  SANIC: "Sanic",
  TURBOGEARS: "TurboGears",
  PYRAMID: "Pyramid",
  DJANGORESTFRAMEWORK: "Django REST Framework",
  FASTAPI: "FastAPI",
  MICRONAUT: "Micronaut",
  QUARKUS: "Quarkus",
  JHIPSTER: "JHipster",
  DROPWIZARD: "Dropwizard",
  AKKA: "Akka",
  VAADIN: "Vaadin",
  HIBERNATE: "Hibernate",
  TENSORFLOW: "TensorFlow",
  PYTORCH: "PyTorch",
  ANGULAR: "Angular",
};

export type Framework = (typeof FrameworkValues)[keyof typeof FrameworkValues];
