export const LanguageValues = {
  PYTHON: "Python",
  JAVASCRIPT: "JavaScript",
  JAVA: "Java",
  CPP: "C++",
  CSHARP: "C#",
  TYPESCRIPT: "TypeScript",
  PHP: "PHP",
  SWIFT: "Swift",
  KOTLIN: "Kotlin",
  GO: "Go",
  RUBY: "Ruby",
  RUST: "Rust",
  MATLAB: "MATLAB",
  R: "R",
  OBJECTIVEC: "Objective-C",
  PERL: "Perl",
  SCALA: "Scala",
  LUA: "Lua",
  GROOVY: "Groovy",
  SHELL: "Shell",
  POWERSHELL: "PowerShell",
  HTMLCSS: "HTML/CSS",
  DART: "Dart",
  JULIA: "Julia",
  HASKELL: "Haskell",
  COFFEESCRIPT: "CoffeeScript",
  ERLANG: "Erlang",
  FORTRAN: "Fortran",
  APEX: "Apex",
  COBOL: "COBOL",
  PLSQL: "PL/SQL",
  ABAP: "ABAP",
  SCHEME: "Scheme",
  SCRATCH: "Scratch",
  SAS: "SAS",
  LISP: "Lisp",
  ADA: "Ada",
  PROLOG: "Prolog",
  CLOJURE: "Clojure",
  ELIXIR: "Elixir",
  DELPHI: "Delphi/Object Pascal",
  CRYSTAL: "Crystal",
  SMALLTALK: "Smalltalk",
  AWK: "Awk",
  AUTOHOTKEY: "AutoHotkey",
  EIFFEL: "Eiffel",
} as const;

export type Language = (typeof LanguageValues)[keyof typeof LanguageValues];
